export const SAVE_STORE_REQUEST = "SAVE_STORE_REQUEST";
export const SAVE_STORE_SUCCESS = "SAVE_STORE_SUCCESS";
export const SAVE_STORE_FAIL = "SAVE_STORE_FAIL";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

export const STORE_LIST_REQUEST = "STORE_LIST_REQUEST";
export const STORE_LIST_SUCCESS = "STORE_LIST_SUCCESS";
export const STORE_LIST_FAIL = "STORE_LIST_FAIL";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";


export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const SEARCH_ONE_REQUEST = "SEARCH_ONE_REQUEST";
export const SEARCH_ONE_SUCCESS = "SEARCH_ONE_SUCCESS";
export const SEARCH_ONE_FAIL = "SEARCH_ONE_FAIL";